name: '🚀 Feature request'
labels: 'enhancement'
description: I have a suggestion

body:
  - type: textarea
    attributes:
      label: What feature do you want to see added?
      description: A clear and concise description of your feature request.
    validations:
      required: true